# -*- coding: utf-8 -*-
"""Bayes Back Progation Project file

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgSUliuEvz_l-QI9rXMB4j-efGJXFxvj
"""

# First we are going to load up our packages
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

# Using pandas package we get
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/concrete/compressive/Concrete_Data.xls"
concrete = pd.read_excel(url)
print(concrete)
#Cement- (kg/m^3)
#Blast Furnace Slag- (kg/m^3)
#Fly Ash-(kg/m^3)
#Water-(kg/m^3)
#Superplasticizer-(kg/m^3)
#Coarse Aggregate-(kg/m^3)
#Fine Aggregate-(kg/m^3)
#Age-(days)-(kg/m^3)
#Concrete compressive strength (DEPENDENT)- (MPA, megapascals)

x = concrete.iloc[:,:-1].values # first 8 columns
y= concrete.iloc[:,-1].values  # concrete strength

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=42)
# to train and test split data

# standardizing training testing for both x and y,
scalar_x = StandardScaler()
x_train_scaled=scalar_x.fit_transform(x_train)
x_test_scaled=scalar_x.transform(x_test)

# Standarizing y
y_mean = y_train.mean()
y_std = y_train.std()
y_train_scaled = (y_train - y_mean)/ y_std
y_test_scaled = (y_test - y_mean)/y_std
# The reason is for better numeric stability

#Now we have to convert our data into tensors within Pytorch library

x_train_tensor = torch.tensor(x_train_scaled,dtype=torch.float32)
x_test_tensor = torch.tensor(x_test_scaled,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train_scaled,dtype=torch.float32).unsqueeze(1)
y_test_tensor = torch.tensor(y_test_scaled,dtype=torch.float32).unsqueeze(1)

train_dataset=TensorDataset(x_train_tensor,y_train_tensor)
train_loader = DataLoader(train_dataset,batch_size=32, shuffle=True)
# We are combining the training data set and our data loader is helping
# reduce and optimize the data into batches and randomizes it by shuffling.
# All this so that its computational more efficent

class BayesianLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight_mu = nn.Parameter(torch.Tensor(out_features, in_features).normal_(0, 0.1))
        self.bias_mu = nn.Parameter(torch.Tensor(out_features).normal_(0, 0.1))
        self.weight_rho = nn.Parameter(torch.Tensor(out_features, in_features).uniform_(-5, -4))
        self.bias_rho = nn.Parameter(torch.Tensor(out_features).uniform_(-5, -4))
        self.softplus = nn.Softplus()

    def forward(self, x):
        weight_sigma = self.softplus(self.weight_rho)
        bias_sigma = self.softplus(self.bias_rho)
        weight_eps = torch.randn_like(self.weight_mu)
        bias_eps = torch.randn_like(self.bias_mu)
        weight = self.weight_mu + weight_sigma * weight_eps
        bias= self.bias_mu + bias_sigma * bias_eps
        return F.linear(x, weight, bias)

    def kl_loss(self):
        weight_sigma= self.softplus(self.weight_rho)
        bias_sigma= self.softplus(self.bias_rho)
        weight_kl = (torch.log(1.0 / weight_sigma) + (weight_sigma**2 + self.weight_mu**2)/2 - 0.5).sum()
        bias_kl= (torch.log(1.0 / bias_sigma) + (bias_sigma**2 + self.bias_mu**2)/2 - 0.5).sum()
        return weight_kl + bias_kl



class BayesByBackpropNN(nn.Module):
    def __init__(self,input_dim):
      super().__init__()
      self.b1 = BayesianLinear(input_dim,64)
      self.b2 = BayesianLinear(64,64)
      self.b3 = BayesianLinear(64,1)
      self.relu= nn.ReLU()

    def forward(self,x):
      k1=0
      x= self.relu(self.b1(x))
      k1 += self.b1.kl_loss()
      x= self.relu(self.b2(x))
      k1 += self.b2.kl_loss()
      x= self.b3(x)
      k1 += self.b3.kl_loss()
      return x,k1
      # we are keeping track of the KL from the first layer
      #so that we can measure how far each layers weights/biases are from the prior

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = BayesByBackpropNN(x_train.shape[1]).to(device)

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
epochs = 50
kl_weight = 1.0 / len(train_loader)


for epoch in range(epochs):
    model.train()
    running_loss = 0
    for x_batch, y_batch in train_loader:
        x_batch = x_batch.to(device)
        y_batch = y_batch.to(device)
        optimizer.zero_grad()
        pred, kl = model(x_batch)
        loss = criterion(pred, y_batch) + kl_weight * kl
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * x_batch.size(0)
    epoch_loss = running_loss / len(train_loader.dataset)
    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {epoch_loss:.4f}")

mc_samples = 2000
model.eval()
predictions = []

with torch.no_grad():
    for _ in range(mc_samples):
        pred, _ = model(x_test_tensor.to(device))
        predictions.append(pred.cpu().numpy())

predictions = np.stack(predictions,axis=0)
y_pred_mean = predictions.mean(axis=0).squeeze()
y_pred_std = predictions.std(axis=0).squeeze()
y_pred_original = y_pred_mean * y_std + y_mean

mse = mean_squared_error(y_test, y_pred_original)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_original)
print(f"MSE: {mse:.4f}, RMSE: {rmse:.4f}, R^2: {r2:.4f}")

plt.figure(figsize=(6,4))

# Predicted vs actual with error bars
plt.errorbar(y_test,y_pred_original, yerr=y_pred_std * y_std,  fmt='o',alpha=0.6,
label='Predictions ± error')
plt.scatter(y_test, y_test,color='r',alpha=0.8,label='True values')
plt.xlabel("Actual Concrete Compressive Strength (MPa)")
plt.ylabel("Predicted Concrete Compressive Strength (MPa)")
plt.title("Predicted vs Actual Concrete Compressive Strength")
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
sorted_idx = np.argsort(y_test)
y_test_sorted = y_test[sorted_idx]
y_pred_sorted = y_pred_original[sorted_idx]
y_err_sorted = (y_pred_std * y_std)[sorted_idx]
x_sorted = np.arange(len(y_test_sorted))
plt.scatter(x_sorted, y_test_sorted, color='r',alpha=0.8,label='Actual test values')
plt.errorbar(x_sorted, y_pred_sorted, yerr=y_err_sorted,fmt='o',alpha=0.6,label='Predictions +- error')
plt.xlabel("Test Observations Sorted")
plt.ylabel("Concrete Compressive Strength (MPa)")
plt.title(" Predicted vs Actual test data")
plt.legend()
plt.tight_layout()
plt.show()

from google.colab import files
uploaded = files.upload()

drone = pd.read_csv("exam1.csv")
drone.head()

x = drone.iloc[:,0].values
y= drone.iloc[:,1].values
print(x.shape)

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=42)
print(x_train.shape, x_test.shape)

x_train = x_train.reshape(-1, 1)
x_test = x_test.reshape(-1, 1)

scalar_x = StandardScaler()
x_train_scaled=scalar_x.fit_transform(x_train)
x_test_scaled=scalar_x.transform(x_test)

y_mean = y_train.mean()
y_std = y_train.std()
y_train_scaled = (y_train - y_mean)/ y_std
y_test_scaled = (y_test - y_mean)/y_std

x_train_tensor = torch.tensor(x_train_scaled,dtype=torch.float32)
x_test_tensor = torch.tensor(x_test_scaled,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train_scaled,dtype=torch.float32).unsqueeze(1)
y_test_tensor = torch.tensor(y_test_scaled,dtype=torch.float32).unsqueeze(1)

train_dataset=TensorDataset(x_train_tensor,y_train_tensor)
train_loader = DataLoader(train_dataset,batch_size=32, shuffle=True)

class BayesianLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight_mu = nn.Parameter(torch.Tensor(out_features, in_features).normal_(0, .5))
        self.bias_mu = nn.Parameter(torch.Tensor(out_features).normal_(0, .5))
        self.weight_rho = nn.Parameter(torch.Tensor(out_features, in_features).uniform_(-2, -0.5))
        self.bias_rho = nn.Parameter(torch.Tensor(out_features).uniform_(-2, -0.5))
        self.softplus = nn.Softplus()

    def forward(self, x):
        weight_sigma = self.softplus(self.weight_rho)
        bias_sigma = self.softplus(self.bias_rho)
        weight_eps = torch.randn_like(self.weight_mu)
        bias_eps = torch.randn_like(self.bias_mu)
        weight = self.weight_mu + weight_sigma * weight_eps
        bias= self.bias_mu + bias_sigma * bias_eps
        return F.linear(x, weight, bias)

    def kl_loss(self):
        weight_sigma= self.softplus(self.weight_rho)
        bias_sigma= self.softplus(self.bias_rho)
        weight_kl = (torch.log(1.0 / weight_sigma) + (weight_sigma**2 + self.weight_mu**2)/2 - 0.5).sum()
        bias_kl= (torch.log(1.0 / bias_sigma) + (bias_sigma**2 + self.bias_mu**2)/2 - 0.5).sum()
        return weight_kl + bias_kl

class BayesByBackpropNN(nn.Module):
    def __init__(self,input_dim):
      super().__init__()
      self.b1 = BayesianLinear(input_dim,64)
      self.b2 = BayesianLinear(64,32)
      self.b3 = BayesianLinear(32,1)
      self.Tan= nn.Tanh()

    def forward(self,x):
      k1=0
      x= self.Tan(self.b1(x))
      k1 += self.b1.kl_loss()
      x= self.Tan(self.b2(x))
      k1 += self.b2.kl_loss()
      x= self.b3(x)
      k1 += self.b3.kl_loss()
      return x,k1

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = BayesByBackpropNN(x_train.shape[1]).to(device)

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
epochs = 3000
kl_weight = 0.01/ len(train_loader)


for epoch in range(epochs):
    model.train()
    running_loss = 0
    for x_batch, y_batch in train_loader:
        x_batch = x_batch.to(device)
        y_batch = y_batch.to(device)
        optimizer.zero_grad()
        pred, kl = model(x_batch)
        loss = criterion(pred, y_batch) + kl_weight * kl
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * x_batch.size(0)
    epoch_loss = running_loss / len(train_loader.dataset)
    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {epoch_loss:.4f}")

mc_samples = 2000
model.eval()
predictions = []

with torch.no_grad():
    for _ in range(mc_samples):
        pred, _ = model(x_test_tensor.to(device))
        predictions.append(pred.cpu().numpy())

predictions = np.stack(predictions,axis=0)
y_pred_mean = predictions.mean(axis=0).squeeze()
y_pred_std = predictions.std(axis=0).squeeze()
y_pred_original = y_pred_mean * y_std + y_mean

mse = mean_squared_error(y_test, y_pred_original)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_original)
print(f"MSE: {mse:.4f}, RMSE: {rmse:.4f}, R^2: {r2:.4f}")

plt.figure(figsize=(6,4))

# Predicted vs actual with error bars
plt.errorbar(y_test,y_pred_original, yerr=y_pred_std * y_std,  fmt='o',alpha=0.6,
label='Predictions +- error')
plt.scatter(y_test, y_test,color='r',alpha=0.8,label='True values')
plt.xlabel("Error (meters)")
plt.ylabel("Predicted Error (meters)")
plt.title("Predicted vs Actual Actual Error(meters)")
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
# Plot actual data points
plt.scatter(x_test, y_test, color='blue', alpha=0.6, label='Actual Data')

sorted_idx = np.argsort(x_test.reshape(-1))
x_sorted = x_test[sorted_idx].reshape(-1)
y_pred_sorted = y_pred_original[sorted_idx]
ci_up = np.percentile(predictions, 97.5, axis=0).squeeze()
ci_low = np.percentile(predictions, 2.5, axis=0).squeeze()
ci_up_sorted = ci_up[sorted_idx]
ci_low_sorted = ci_low[sorted_idx]
pred_std_original = y_pred_std * y_std
lower = y_pred_original - 2 * pred_std_original
upper = y_pred_original + 2 * pred_std_original


plt.plot(x_sorted, y_pred_sorted, color='red', linewidth=3, label='Regression Prediction Line')
plt.fill_between(x_sorted, ci_low_sorted ,ci_up_sorted,color='gray', alpha=0.4, label = '95% Credible Interval of MC samples')
plt.fill_between(x_sorted, lower,upper ,color='gray', alpha=0.4, label = '95% Credible Interval of MC samples')
plt.legend()
plt.show()